# Generated by Django 5.0.6 on 2024-06-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_prestamo_multa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='libro',
            new_name='libro_prestamo',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario',
            new_name='usuario_prestamo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
