# Generated by Django 5.0.6 on 2024-06-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_rename_libro_prestamo_libro_prestamo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_multa',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Estado',
            field=models.IntegerField(choices=[(1, 'Préstamo'), (2, 'Entregado'), (3, 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(choices=[(1, 'lector'), (2, 'bibliotecario'), (3, 'administrador')], max_length=20),
        ),
    ]
