# Generated by Django 5.0.6 on 2024-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_multa_estado_multa_alter_prestamo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='estado_multa',
            field=models.IntegerField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Estado',
            field=models.CharField(choices=[('Préstamo', 'Préstamo'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('lector', 'lector'), ('bibliotecario', 'bibliotecario'), ('administrador', 'administrador')], max_length=20),
        ),
    ]
